### ISSUE TITLE
1.0.0-RC.1: lexing error

### ISSUE THREAD

**Issue by uberbrodt** [jeremyjh/dialyxir#193]
Getting the following error in my umbrella project. Previously worked with dialyxir 0.5
```
Finding suitable PLTs
Checking PLT...
[:absinthe_plug, :absinthe_relay, :aws_auth, :commanded, :commanded_eventstore_adapter, :commanded_swarm_registry, :configparser_ex, :conform, :cowboy, :ecto, :elastix, :elixir, :eventstore,:ex_aws, :ex_aws_kinesis, :exconstructor, :exop, :gettext, :kernel, :libcluster, :logger, :logger_file_backend, :mangle, :mix, :morphix, :mox, :org_svc_client, :personality_data_client, :phoenix, :plug_statsd, :profiles, :protobuf, :recommendation_svc_client, :redix, :runtime_tools, :sasl, :statix, :stdlib, :swarm, :timex, :uuid, :vmstats]                                        
Looking up modules in dialyxir_erlang-20.3.6_elixir-1.6.5_deps-dev.plt
Finding applications for dialyxir_erlang-20.3.6_elixir-1.6.5_deps-dev.plt
Finding modules for dialyxir_erlang-20.3.6_elixir-1.6.5_deps-dev.plt
Removing 808 modules from dialyxir_erlang-20.3.6_elixir-1.6.5_deps-dev.plt
Checking 1506 modules in dialyxir_erlang-20.3.6_elixir-1.6.5_deps-dev.plt
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/home/cbrodt/Projects/traitify/profile-svc/profile_service/_build/dev/dialyxir_erlang-20.3.6_elixir-1.6.5_deps-dev.plt',
  files_rec: ['/home/cbrodt/Projects/traitify/profile-svc/profile_service/_build/dev/lib/profile_web/ebin',
   '/home/cbrodt/Projects/traitify/profile-svc/profile_service/_build/dev/lib/profiles/ebin'],
  warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
   :unknown],
  format: nil,
  raw: nil
]
** (throw) {:error, :lexing, 'Elixir.Absinthe.Plugin'}
    lib/dialyxir/pretty_print.ex:8: Dialyxir.PrettyPrint.lex/1
    lib/dialyxir/pretty_print.ex:33: Dialyxir.PrettyPrint.pretty_print/1
    lib/dialyxir/warnings/unknown_function.ex:15: Dialyxir.Warnings.UnknownFunction.format_long/1
    lib/dialyxir/formatter.ex:77: Dialyxir.Formatter.format_warning/2
    lib/dialyxir/formatter.ex:170: anonymous fn/2 in Dialyxir.Formatter.filter_warnings/2
    (elixir) lib/enum.ex:2955: Enum.reject_list/2
    lib/dialyxir/formatter.ex:25: Dialyxir.Formatter.format_and_filter/3
    lib/dialyxir/dialyzer.ex:36: Dialyxir.Dialyzer.Runner.run/2
    lib/dialyxir/dialyzer.ex:52: Dialyxir.Dialyzer.dialyze/3
    lib/mix/tasks/dialyzer.ex:233: Mix.Tasks.Dialyzer.run_dialyzer/2
    lib/mix/tasks/dialyzer.ex:161: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

**Comment by asummers** [comment]
Is it still broken on `a90966d3e9077dbd7dac2d853b09ad2816c84b91`?

`{:dialyxir, git: "https://github.com/jeremyjh/dialyxir", ref: "a90966d3e9077dbd7dac2d853b09ad2816c84b91",  runtime: false}`

**Comment by asummers** [comment]
Oh you're on RC1. Just kidding.

**Comment by sztosz** [comment]
I had 
```
** (throw) {:error, :lexing, 'Elixir.Amnesia'}
    lib/dialyxir/pretty_print.ex:8: Dialyxir.PrettyPrint.lex/1
    lib/dialyxir/pretty_print.ex:33: Dialyxir.PrettyPrint.pretty_print/1
    lib/dialyxir/warnings/unknown_type.ex:15: Dialyxir.Warnings.UnknownType.format_long/1
    lib/dialyxir/formatter.ex:77: Dialyxir.Formatter.format_warning/2
    lib/dialyxir/formatter.ex:170: anonymous fn/2 in Dialyxir.Formatter.filter_warnings/2
    (elixir) lib/enum.ex:2955: Enum.reject_list/2
    lib/dialyxir/formatter.ex:25: Dialyxir.Formatter.format_and_filter/3
    lib/dialyxir/dialyzer.ex:36: Dialyxir.Dialyzer.Runner.run/2
    lib/dialyxir/dialyzer.ex:52: Dialyxir.Dialyzer.dialyze/3
    lib/mix/tasks/dialyzer.ex:233: Mix.Tasks.Dialyzer.run_dialyzer/2
    lib/mix/tasks/dialyzer.ex:161: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```
on `1.0.0-RC.1`, now with `a90966d3e9077dbd7dac2d853b09ad2816c84b91` it works OK. Thanks for fixing :)

**Comment by jeremyjh** [comment]
rc.1 is now on hex too
