### ISSUE TITLE
Exception is raised when run from circleci/elixir:1.6.5 container 

### ISSUE THREAD

**Issue by AndrewDryga** [jeremyjh/dialyxir#195]
```
** (throw) {:error, :lexing, 'Elixir.ExUnit.Callbacks'}
    lib/dialyxir/pretty_print.ex:8: Dialyxir.PrettyPrint.lex/1
    lib/dialyxir/pretty_print.ex:33: Dialyxir.PrettyPrint.pretty_print/1
    lib/dialyxir/warnings/unknown_function.ex:15: Dialyxir.Warnings.UnknownFunction.format_long/1
    lib/dialyxir/formatter.ex:77: Dialyxir.Formatter.format_warning/2
    lib/dialyxir/formatter.ex:170: anonymous fn/2 in Dialyxir.Formatter.filter_warnings/2
    (elixir) lib/enum.ex:2955: Enum.reject_list/2
    lib/dialyxir/formatter.ex:25: Dialyxir.Formatter.format_and_filter/3
    lib/dialyxir/dialyzer.ex:36: Dialyxir.Dialyzer.Runner.run/2
    lib/dialyxir/dialyzer.ex:52: Dialyxir.Dialyzer.dialyze/3
    lib/mix/tasks/dialyzer.ex:233: Mix.Tasks.Dialyzer.run_dialyzer/2
    lib/mix/tasks/dialyzer.ex:161: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

**Comment by asummers** [comment]
This should be fixed on `1.0.0-rc2`. Are you still on rc0 or rc1 by chance?

**Comment by asummers** [comment]
Background on what happened there is that the two `.erl` files generated by Leex and Yecc weren't being included in the hex build, and it was balking on everything. People using it from git had them though which led to all sorts of fun confusion =)

**Comment by AndrewDryga** [comment]
We were on rc0, thank you! :)
