### ISSUE TITLE
{:error, :unknown_warning, :missing_range}

### ISSUE THREAD

**Issue by AndrewDryga** [jeremyjh/dialyxir#205]
I got an exception while running dialyzer on Sage, here is a PR where it reproduces for me:
https://github.com/Nebo15/sage/pull/32

```
** (throw) {:error, :unknown_warning, :missing_range}
    (dialyxir) lib/dialyxir/formatter.ex:170: Dialyxir.Formatter.warning/1
    (dialyxir) lib/dialyxir/formatter.ex:76: Dialyxir.Formatter.format_warning/2
    (dialyxir) lib/dialyxir/formatter.ex:177: anonymous fn/2 in Dialyxir.Formatter.filter_warnings/2
    (elixir) lib/enum.ex:2955: Enum.reject_list/2
    (elixir) lib/enum.ex:2958: Enum.reject_list/2
    (dialyxir) lib/dialyxir/formatter.ex:44: Dialyxir.Formatter.format_and_filter/3
    (dialyxir) lib/dialyxir/dialyzer.ex:42: Dialyxir.Dialyzer.Runner.run/2
    (dialyxir) lib/dialyxir/dialyzer.ex:58: Dialyxir.Dialyzer.dialyze/3
```

**Comment by asummers** [comment]
Is that on OTP 21? I didn't realize there was a new warning. Neat. Can you do me a favor and print that error with `mix dialyzer --format dialyzer` so I know what that error is supposed to look like so I can parse it?

**Comment by AndrewDryga** [comment]
@asummers yeap, it's 21. Command did not work :( :
```
mix dialyzer --format dialyzer
Compiling 14 files (.ex)
Generated sage app
Finding suitable PLTs
Checking PLT...
[:asn1, :certifi, :compiler, :crypto, :dialyxir, :dialyzer, :earmark, :elixir, :ex_doc, :excoveralls, :hackney, :hipe, :idna, :inch_ex, :jason, :kernel, :logger, :metrics, :mimerl, :mix, :public_key, :ssl, :ssl_verify_fun, :stdlib, :unicode_util_compat, :wx]
PLT is up to date!
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/andrew/Projects/os/sage/_build/test/dialyxir_erlang-21.0.1_elixir-1.6.6_deps-test.plt',
  files_rec: ['/Users/andrew/Projects/os/sage/_build/test/lib/sage/ebin'],
  warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
   :overspecs, :unknown]
]
** (throw) {:error, :unknown_warning, :missing_range}
    (dialyxir) lib/dialyxir/formatter.ex:170: Dialyxir.Formatter.warning/1
    (dialyxir) lib/dialyxir/formatter.ex:76: Dialyxir.Formatter.format_warning/2
    (dialyxir) lib/dialyxir/formatter.ex:177: anonymous fn/2 in Dialyxir.Formatter.filter_warnings/2
    (elixir) lib/enum.ex:2955: Enum.reject_list/2
    (elixir) lib/enum.ex:2958: Enum.reject_list/2
    (dialyxir) lib/dialyxir/formatter.ex:44: Dialyxir.Formatter.format_and_filter/3
    (dialyxir) lib/dialyxir/dialyzer.ex:42: Dialyxir.Dialyzer.Runner.run/2
    (dialyxir) lib/dialyxir/dialyzer.ex:58: Dialyxir.Dialyzer.dialyze/3
```

**Comment by asummers** [comment]
Thanks. I'll take a look this evening / weekend. Should be straightforward to add the new warning, just gotta do it. I'd also like to understand why it's not catching that throw properly.

**Comment by asummers** [comment]
Fixed in current master!
