### ISSUE TITLE
--format * does not work 

### ISSUE THREAD

**Issue by joaothallis** [jeremyjh/dialyxir#247]
The folowing command line options does not work: `--format short`, `--format raw`, `--format dialyxir`, `--format dialyzer`
Example:
```elixir
mix dialyzer --format dialyzer
Checking PLT...
[:artificery, :asn1, :bunt, :certifi, :combine, :compiler, :connection, :cowboy,
 :cowlib, :credo, :crypto, :db_connection, :decimal, :dialyxir, :distillery,
 :earmark, :ecto, :eex, :elixir, :ex_doc, :file_system, :gettext, :hackney,
 :idna, :inets, :jason, :kernel, :logger, :makeup, :makeup_elixir, :metrics,
 :mime, :mimerl, :nimble_parsec, :parse_trans, :phoenix, :phoenix_ecto,
 :phoenix_html, :phoenix_live_reload, :phoenix_pubsub, :plug, :poison, :poolboy,
 :postgrex, :public_key, :ranch, :runtime_tools, :ssl, :ssl_verify_fun, :stdlib,
 ...]
PLT is up to date!
Starting Dialyzer
dialyzer args: [
  check_plt: false,
  init_plt: '/home/joao/code/src/github.com/joaothallis/key/_build/dev/dialyxir_erlang-21.0.8_elixir-1.7.3_deps-dev.plt',
  files_rec: ['/home/joao/code/src/github.com/joaothallis/key/_build/dev/lib/key/ebin'],
  warnings: [:format, :unknown]
]
:dialyzer.run error: Unknown dialyzer warning option: format
```

**Comment by asummers** [comment]
I'm curious how you're getting that. When I run that command I get:

```
 mix dialyzer --format short
Finding suitable PLTs
Checking PLT...
[:compiler, :elixir, :erlex, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/home/asummers/Code/demolyzer/_build/dev/dialyxir_erlang-21.0.9_elixir-1.7.1_deps-dev.plt',
  files_rec: ['/home/asummers/Code/demolyzer/_build/dev/lib/demolyzer/ebin'],
  warnings: [:unknown]
]
done in 0m0.98s
lib/demolyzer.ex:4:guard_fail Guard test can never succeed.

```

My guess is you have an archive installed globally. Try running `mix archive` and seeing if there's a `dialyxir` of some form there, then `mix archive.uninstall <name>` there.

**Comment by joaothallis** [comment]
When I run mix archive, I have this return: 
```bash
* hex-0.18.1
* phx_new
Archives installed at: /home/joao/.mix/archives
```

I followed these steps to configure Dialyxir: https://github.com/jeremyjh/dialyxir/wiki/Phoenix-Dialyxir-Quickstart

My project: https://github.com/joaothallis/key

**Comment by asummers** [comment]
Those instructions are out of date to the current release candidate that added the new formatting. Change the version of your `dialyxir` in your `mix.lock` from `0.5.1` to `1.0.0-rc3`.

**Comment by joaothallis** [comment]
After installing globally, I get the following error:
```elixir
mix dialyzer
** (UndefinedFunctionError) function Dialyxir.Output.info/1 is undefined or private
    Dialyxir.Output.info("Finding suitable PLTs")
    lib/mix/tasks/dialyzer.ex:155: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

**Comment by asummers** [comment]
Yeah you should uninstall globally. Sorry about that! Check my post above and you should be all good :smile:
