### ISSUE TITLE
Erlang/OTP 18 compatibility

### ISSUE THREAD

**Issue by my-flow** [jeremyjh/dialyxir#26]
I'm using Elixir 1.0.5. After upgrading from OTP 17.5 to 18.0 the core build fails.

```
fbreunig@Cod:~/Workspace/dialyxir (master) 🍔  mix dialyzer.plt
Starting PLT Core Build ... this will take awhile
dialyzer --output_plt /Users/fbreunig/.dialyxir_core_18_1.0.5.plt --build_plt --apps erts kernel stdlib crypto public_key -r /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../eex/ebin /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../ex_unit/ebin /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../iex/ebin /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin
  Compiling some key modules to native code... done in 0m0.28s
  Creating PLT /Users/fbreunig/.dialyxir_core_18_1.0.5.plt ...
dialyzer: Analysis failed with error:
Could not scan the following file(s):
  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin/Elixir.Mix.NoTaskError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin/Elixir.Mix.NoProjectError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin/Elixir.Mix.InvalidTaskError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin/Elixir.Mix.Error.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin/Elixir.Mix.ElixirVersionError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin/Elixir.Mix.Dep.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../mix/ebin/Elixir.Mix.Config.LoadError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../iex/ebin/Elixir.IEx.State.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../ex_unit/ebin/Elixir.ExUnit.TimeoutError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../ex_unit/ebin/Elixir.ExUnit.TestCase.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../ex_unit/ebin/Elixir.ExUnit.Test.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../ex_unit/ebin/Elixir.ExUnit.DocTest.Error.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../ex_unit/ebin/Elixir.ExUnit.AssertionError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Version.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Version.Requirement.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Version.InvalidVersionError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.UnicodeConversionError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Version.InvalidRequirementError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.UndefinedFunctionError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.URI.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.TryClauseError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.TokenMissingError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Task.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.SystemLimitError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.System.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.SyntaxError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Supervisor.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Stream.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.RuntimeError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Regex.CompileError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Regex.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Range.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Protocol.UndefinedError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.MatchError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Macro.Env.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.KeyError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Inspect.Opts.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.IO.StreamError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.IO.Stream.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.HashSet.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.HashDict.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.FunctionClauseError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.File.Error.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.GenEvent.Stream.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.File.CopyError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.File.Stream.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.ErlangError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.File.Stat.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Exception.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Enum.OutOfBoundsError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Enum.EmptyError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.CondClauseError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.CompileError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.Code.LoadError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.CaseClauseError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.BadStructError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.BadMapError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.BadFunctionError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.BadArityError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.ArithmeticError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../elixir/ebin/Elixir.ArgumentError.beam  Could not get core Erlang code for: /usr/local/Cellar/elixir/1.0.5/bin/../lib/elixir/../eex/ebin/Elixir.EEx.SyntaxError.beam
Last messages in the log cache:
  Reading files and computing callgraph...

** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:118: Keyword.get(:no_such_file, :files, nil)
    lib/mix/tasks/dialyzer.plt.ex:132: Mix.Tasks.Dialyzer.Plt.core_plt_contains?/2
    lib/mix/tasks/dialyzer.plt.ex:123: anonymous fn/1 in Mix.Tasks.Dialyzer.Plt.missing_apps/0
    (elixir) lib/enum.ex:662: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:662: Enum.filter/2
    lib/mix/tasks/dialyzer.plt.ex:106: Mix.Tasks.Dialyzer.Plt.need_add?/0
    lib/mix/tasks/dialyzer.plt.ex:57: Mix.Tasks.Dialyzer.Plt.run/1
```

**Comment by jeremyjh** [comment]
Elixir will not support Erlang 18 until v 1.2: https://github.com/elixir-lang/elixir/issues/3212
