### ISSUE TITLE
crash on `--format short`

### ISSUE THREAD

**Issue by k-cross** [jeremyjh/dialyxir#265]
```
** (throw) {:error, :unknown_warning, :contract_range}
    lib/dialyxir/formatter.ex:170: Dialyxir.Formatter.warning/1
    lib/dialyxir/formatter.ex:76: Dialyxir.Formatter.format_warning/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    lib/dialyxir/dialyzer.ex:42: Dialyxir.Dialyzer.Runner.run/2
    lib/dialyxir/dialyzer.ex:58: Dialyxir.Dialyzer.dialyze/3
    lib/mix/tasks/dialyzer.ex:225: Mix.Tasks.Dialyzer.run_dialyzer/2
    lib/mix/tasks/dialyzer.ex:159: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

I'll try to help where I can, but running this with the format short option causes a crash. I'll update or close the ticket if it works on master.

**Comment by jeremyjh** [comment]
This should be fixed already on master. Also I think it would crash without `--format short`. Can you confirm?

**Comment by k-cross** [comment]
It doesn't crash running plain `mix dialyzer` that's why I specified the option. Or did you mean something else?

**Comment by k-cross** [comment]
I'll checkout master in about an hour, I'm running to a meeting and might be able to try it there :)

**Comment by k-cross** [comment]
@jeremyjh this works on master, thank you!
