### ISSUE TITLE
Format Short Broken

### ISSUE THREAD

**Issue by jeremyjh** [jeremyjh/dialyxir#281]
After merge #278 I noticed `mix dialyzer --format short` fails with an error in this repository itself:

```
** (CaseClauseError) no case clause matching: []
    lib/dialyxir/dialyzer.ex:47: Dialyxir.Dialyzer.Runner.run/2
    lib/dialyxir/dialyzer.ex:71: Dialyxir.Dialyzer.dialyze/3
    lib/mix/tasks/dialyzer.ex:258: Mix.Tasks.Dialyzer.run_dialyzer/2
    lib/mix/tasks/dialyzer.ex:190: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

@evnu do you mind taking a look? I'm guessing the `:short` clause needs similar updates to the `:dialyxir` format clause.

**Comment by evnu** [comment]
Yes, I will look into it.
