### ISSUE TITLE
Sudden Strange Problem with rc5 and rc6

### ISSUE THREAD

**Issue by jherdman** [jeremyjh/dialyxir#319]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir): 1.0.0.rc6 (same issue with rc5)

### Current behavior

Suddenly I'm seeing this error:

```
Finding suitable PLTs
Checking PLT...
[:asn1, :base64url, :bcrypt_elixir, :bunt, :certifi, :comeonin, :compiler, :connection, :cors_plug, :cowboy, :cowlib, :credo, :crypto, :db_connection, :decimal, :dialyxir, :ecto, :ecto_sql, :eex, :elixir, :elixir_make, :erlex, :feeder, :feeder_ex, :gettext, :guardian, :hackney, :httpoison, :idna, :inets, :jason, :jose, :jsonapi, :kernel, :logger, :metrics, :mime, :mimerl, :new_relic_agent, :new_relic_phoenix, :os_mon, :parse_trans, :phoenix, :phoenix_ecto, :phoenix_pubsub, :plug, :plug_cowboy, :plug_crypto, :postgrex, :public_key, ...]
Looking up modules in dialyzer.plt
Finding applications for dialyzer.plt
Finding modules for dialyzer.plt
Removing 428 modules from dialyzer.plt
** (CaseClauseError) no case clause matching: {{:nocatch, {:dialyzer_error, [78, 111, 116, 32, 97, 32, 114, 101, 103, 117, 108, 97, 114, 32, 102, 105, 108, 101, 58, 32, '/usr/local/Cellar/erlang/21.3.2/lib/erlang/lib/hipe-3.18.3/ebin/erl_bif_types.beam', 10]}}, [{:dialyzer_plt, :compute_md5_from_file, 1, [file: 'dialyzer_plt.erl', line: 543]}, {:dialyzer_plt, :compute_new_md5_1, 3, [file: 'dialyzer_plt.erl', line: 509]}, {:dialyzer_plt, :check_version, 1, [file: 'dialyzer_plt.erl', line: 328]}, {:dialyzer_plt, :check_plt1, 3, [file: 'dialyzer_plt.erl', line: 477]}, {:dialyzer_plt, :"-subproc/1-fun-0-", 1, [file: 'dialyzer_plt.erl', line: 603]}]}
    dialyzer_cl.erl:249: :dialyzer_cl.check_plt/3
    dialyzer_cl.erl:182: :dialyzer_cl.plt_common/3
    dialyzer.erl:160: :dialyzer.run/1
    lib/dialyxir/plt.ex:209: Dialyxir.Plt.plt_run/1
    lib/dialyxir/plt.ex:189: Dialyxir.Plt.plt_remove/2
    lib/dialyxir/plt.ex:144: Dialyxir.Plt.check_beams/3
    lib/dialyxir/plt.ex:43: Dialyxir.Plt.check_plt/4
    (el
11:14:51.585 [error] Process #PID<0.361.0> raised an exception
** (ErlangError) Erlang error: {:nocatch, {:dialyzer_error, [78, 111, 116, 32, 97, 32, 114, 101, 103, 117, 108, 97, 114, 32, 102, 105, 108, 101, 58, 32, '/usr/local/Cellar/erlang/21.3.2/lib/erlang/lib/hipe-3.18.3/ebin/erl_bif_types.beam', 10]}}
    dialyzer_plt.erl:543: :dialyzer_plt.compute_md5_from_file/1
    dialyzer_plt.erl:509: :dialyzer_plt.compute_new_md5_1/3
    dialyzer_plt.erl:328: :dialyzer_plt.check_version/1
    dialyzer_plt.erl:477: :dialyzer_plt.check_plt1/3
    dialyzer_plt.erl:603: anonymous fn/1 in :dialyzer_plt.subproc/1
ixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/dialyzer.ex:246: Mix.Tasks.Dialyzer.check_plt/1
    lib/mix/tasks/dialyzer.ex:167: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

I think the change is a recent Erlang update being installed by Homebrew when one installs Elixir.

### Expected behavior

It works again 😄

**Comment by asummers** [comment]
Try clearing your PLTs. When you bump your Elixir or Erlang version it has to rebuild the whole PLT. If that works, I'm not sure the root cause necessarily, but we can work from there.

**Comment by jherdman** [comment]
Worked like a charm! Many thanks for the help.

**Comment by jeremyjh** [comment]
The elixir and Erlang version is part of the PLT name by default. Does your
config specify a PLT name?

**Comment by jherdman** [comment]
Yeah, my configuration is like this:

```elixir
  defp dialyzer do
    [
      plt_file: {:no_warn, "priv/plts/dialyzer.plt"},
      plt_add_deps: :app_tree
    ]
  end
```

I'm doing this to have it in a predictable place to cache between builds on
my CI server.

**Comment by sashaafm** [comment]
Would it be possible to add a warning message in the error suggesting that the solution may be clearing the old PLTs?
