### ISSUE TITLE
Not sure how to debug issue. 

### ISSUE THREAD

**Issue by joshchernoff** [jeremyjh/dialyxir#350]
```
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/app/_build/dev/dialyxir_erlang-22.0.3_elixir-1.9.0_deps-dev.plt',
  files_rec: ['/app/_build/dev/lib/insights/ebin'],
  warnings: [:unknown]
]
** (MatchError) no match of right hand side value: {:error, {1, :erl_parse, ['syntax error before: ', '\'::\'']}}
    dialyzer.erl:626: anonymous fn/1 in :dialyzer.sig/2
    dialyzer.erl:541: :dialyzer.call_or_apply_to_string/6
    dialyzer.erl:322: :dialyzer.message_to_string/2
    dialyzer.erl:297: :dialyzer.format_warning/2
    lib/dialyxir/formatter.ex:106: Dialyxir.Formatter.format_warning/2
    lib/dialyxir/formatter.ex:275: anonymous fn/2 in Dialyxir.Formatter.filter_legacy_warnings/2
    (elixir) lib/enum.ex:3029: Enum.reject_list/2
    (elixir) lib/enum.ex:3032: Enum.reject_list/2
    lib/dialyxir/formatter.ex:32: Dialyxir.Formatter.format_and_filter/4
    lib/dialyxir/dialyzer.ex:47: Dialyxir.Dialyzer.Runner.run/2
    lib/dialyxir/dialyzer.ex:74: Dialyxir.Dialyzer.dialyze/3
    lib/mix/tasks/dialyzer.ex:263: Mix.Tasks.Dialyzer.run_dialyzer/2
    lib/mix/tasks/dialyzer.ex:195: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

What is this telling me? 

Running elixir 1.9 OTP 22.0.3 found that even after I removed all `@spec` and `@type` from code I was still getting this error.

**Comment by dhedlund** [comment]
This looks like the same issue as #341 and #343.  Need to bump your version of erlang to 22.0.5.

**Comment by joshchernoff** [comment]
Awesome thanks bud
