### ISSUE TITLE
compile error with --format ignore_file

### ISSUE THREAD

**Issue by dvic** [jeremyjh/dialyxir#510]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Elixir 1.15.2 and OTP 26.0.2

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):
1.3.0

### Current behavior
Running `mix dialyzer --format ignore_file` gives the following error:

```
** (SyntaxError) nofile:1:9: syntax error before: suitable
    |
  1 | Finding suitable PLTs
    |         ^
    (elixir 1.15.2) lib/code.ex:542: Code.validated_eval_string/3
    (dialyxir 1.3.0) lib/dialyxir/filter_map.ex:22: Dialyxir.FilterMap.from_file/3
    (dialyxir 1.3.0) lib/dialyxir/formatter.ex:26: Dialyxir.Formatter.format_and_filter/4
    (dialyxir 1.3.0) lib/dialyxir/dialyzer.ex:59: Dialyxir.Dialyzer.Runner.run/2
    (dialyxir 1.3.0) lib/dialyxir/dialyzer.ex:81: Dialyxir.Dialyzer.dialyze/3
    (dialyxir 1.3.0) lib/mix/tasks/dialyzer.ex:271: Mix.Tasks.Dialyzer.run_dialyzer/2
    (dialyxir 1.3.0) lib/mix/tasks/dialyzer.ex:203: Mix.Tasks.Dialyzer.run/1
```

**Comment by dvic** [comment]
Omg, never mind, I had the .dialyzer_ignore.exs filled with random text 😄.
