### ISSUE TITLE
`mix dialyze` fails with an error when creating the PLT

### ISSUE THREAD

**Issue by darthdeus** [jeremyjh/dialyxir#75]
When I run `mix dialyze` using dialyxir I get the following error

```
Finding suitable PLTs
Looking up modules in dialyxir_erlang-19.2_elixir-1.4.1_deps-dev.plt
Looking up modules in dialyxir_erlang-19.2_elixir-1.4.1.plt
Looking up modules in dialyxir_erlang-19.2.plt
Finding applications for dialyxir_erlang-19.2.plt
Finding modules for dialyxir_erlang-19.2.plt
Creating dialyxir_erlang-19.2.plt
** (throw) {:dialyzer_error, [67, 111, 117, 108, 100, 32, 110, 111, 116, 32, 103, 101, 116, 32, 97, 98, 115, 116, 114, 97, 99, 116, 32, 99, 111, 100, 101, 32, 102, 111, 114, 32, 102, 105, 108, 101, 58, 32, '/usr/lib/erlang/lib/erts-8.2/ebin/erlang.beam', 32, 40, 112, 108, 101, 97, 115, 101, 32, 114, ...]}
    dialyzer_plt.erl:469: :dialyzer_plt.compute_md5_from_file/1
    dialyzer_plt.erl:458: :dialyzer_plt."-compute_md5_from_files/1-lc$^0/1-0-"/1
    dialyzer_plt.erl:458: :dialyzer_plt."-compute_md5_from_files/1-lc$^0/1-0-"/1
    dialyzer_plt.erl:458: :dialyzer_plt.compute_md5_from_files/1
    dialyzer_cl.erl:74: :dialyzer_cl.build_plt/1
    dialyzer.erl:167: :dialyzer.run/1
    lib/dialyxir/plt.ex:148: Dialyxir.Plt.plt_new/1
    lib/dialyxir/plt.ex:120: Dialyxir.Plt.check_beams/4
    lib/dialyxir/plt.ex:41: Dialyxir.Plt.check_plt/4
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/dialyxir/plt.ex:28: Dialyxir.Plt.check_plts/1
    lib/mix/tasks/dialyzer.ex:128: Mix.Tasks.Dialyzer.check_plt/0
    lib/mix/tasks/dialyzer.ex:110: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

Since this fails before reaching any of my application's code, I'd asume it's either installation issue, or a bug in dialyxir?

I'm using Elixir 1.4.1 with Erlang 19 on arch linux installed via pacman.

**Comment by jeremyjh** [comment]
@darthdeus You've run  into a [bug](https://bugs.erlang.org/browse/ERL-340) in Erlang RTS use of zlib that is exposed in zlib 1.2.9 (madler/zlib#206) and greater. The easiest workaround for now is to install zlib 1.2.8 from your pacman cache and set it as IgnorePkg in your pacman.conf. There is also a (patch)[http://erlang.org/pipermail/erlang-bugs/2017-January/005213.html] available for Erlang if you'd rather build Erlang from source. It looks like there will be a patch release for it in 19.2.3 but that hasn't been released yet.

**Comment by jeremyjh** [comment]
By the way, 19.2.3 was released on Arch on 2/17 and does fix this issue.
